spring:
  application:
    name: backend
  jpa:
    hibernate:
      ddl-auto: update

management:
  endpoints:
    web:
      base-path: /
      path-mapping:
        health: health
  endpoint:
    health:
      show-details: always

springdoc:
  swagger-ui:
    path: /docs
  show-actuator: true
